---
title: "注意力测试_demo"
author: "【哥，我没有选题了】小组"
date: "2020/09/04"
output:
  html_document:
    toc: true
runtime: shiny
number_sections: true
---
我们组有`r 6 + 2`个人

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```
<font face="黑体">我是黑体字</font>
<font face="微软雅黑">我是微软雅黑</font>
<font face="STCAIYUN">我是华文彩云</font>
<font color=red>我是红色</font>
<font color=#008000>我是绿色</font>
<font color=Blue>我是蓝色</font>
<font size=5>我是尺寸</font>
<font face="黑体" color=green size=5>我是黑体，绿色，尺寸为5</font>

想看更多点击这个[网站](http://rmarkdown.rstudio.com/authoring_shiny.html).

## 造成车祸的原因大多是人为因素

让我们来模拟一下各个情景下的车内视角，看看你的注意力如何

```{r eruptions, echo=FALSE}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c("正常", "疲劳", "嗑药", "酒驾"), selected = "正常"),
  
  sliderInput("bw_adjust", label = "车速（KM/H）:",
              min = 30, max = 120, value = 10, step = 10)
)


```

## 天气也是一大因素

01 让我们试试在不同天气下驾驶吧

<object data="https://games.gdevelop-app.com/game-2a3fed53-a325-4527-b023-b7e6d88e36b5/index.html" width="700" height="500" type="text/html">
    Alternative Content
</object>

02 让我们试试在不同天气下驾驶吧

<embed src="https://games.gdevelop-app.com/game-2a3fed53-a325-4527-b023-b7e6d88e36b5/index.html" width=700 height=500 />

03 让我们试试在不同天气下驾驶吧

 <iframe src='https://games.gdevelop-app.com/game-2a3fed53-a325-4527-b023-b7e6d88e36b5/index.html' ></iframe>
#canvas height="450" width="750"></canvas>
#<script type="text/javascript" src="car/js/main.js"></script>